version: '3.9'

networks:
  songs-network:
    name: songs

services:
  mongo:
    container_name: ${MONGODB_NAME}
    image: mongo:${MONGODB_VERSION}
    ports:
      - ${MONGODB_PORT_EXTERNAL}:27017
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      TZ: "America/Fortaleza"
    command: [ --auth ]
    networks:
      - songs-network
    restart: always
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  songs-api:
    env_file: .env
    container_name: ${CONTEINER_NAME}
    build: .
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - ${SONGS_PORT_EXTERNAL}:8082
    networks:
      - songs-network
    restart: always